In [1]:
#Pandas is mainly used for data analysis. Pandas allows importing data from various file formats such as comma-separated values, JSON, SQL, Microsoft Excel. Pandas allows various data manipulation operations such as merging, reshaping, selecting, as well as data cleaning, and data wrangling features.
#import pandas means importing All pandas functonalities.
import pandas

In [2]:
#Reading the whole data with the help of pandas
db = pandas.read_csv("Salary_Data.csv")

In [3]:
#It helps to tell the coloums heading and datatype
db.columns

Index(['YearsExperience', 'Salary'], dtype='object')

In [4]:
#info tells the all information in the file
db.info

<bound method DataFrame.info of     YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0>

In [5]:
#It includes all the data of coloum 'yearsexperience' to x.
x= db["YearsExperience"]

In [6]:
#It shows all the values that are assigned to x i.e 'yearsexperience'
x

0      1.1
1      1.3
2      1.5
3      2.0
4      2.2
5      2.9
6      3.0
7      3.2
8      3.2
9      3.7
10     3.9
11     4.0
12     4.0
13     4.1
14     4.5
15     4.9
16     5.1
17     5.3
18     5.9
19     6.0
20     6.8
21     7.1
22     7.9
23     8.2
24     8.7
25     9.0
26     9.5
27     9.6
28    10.3
29    10.5
Name: YearsExperience, dtype: float64

In [7]:
# It will reshape and convert the data from 1D to 2D.
x = db['YearsExperience'].values.reshape(30,1)

In [8]:
# input of the data to train the model/It is also called as feature
x

array([[ 1.1],
       [ 1.3],
       [ 1.5],
       [ 2. ],
       [ 2.2],
       [ 2.9],
       [ 3. ],
       [ 3.2],
       [ 3.2],
       [ 3.7],
       [ 3.9],
       [ 4. ],
       [ 4. ],
       [ 4.1],
       [ 4.5],
       [ 4.9],
       [ 5.1],
       [ 5.3],
       [ 5.9],
       [ 6. ],
       [ 6.8],
       [ 7.1],
       [ 7.9],
       [ 8.2],
       [ 8.7],
       [ 9. ],
       [ 9.5],
       [ 9.6],
       [10.3],
       [10.5]])

In [9]:
#It includes all the data of coloum 'Salary' to y.
y = db["Salary"]

In [10]:
#It shows all the values that are assigned to x i.e 'Salary'
#It is the output value which is requires when we predict
y

0      39343.0
1      46205.0
2      37731.0
3      43525.0
4      39891.0
5      56642.0
6      60150.0
7      54445.0
8      64445.0
9      57189.0
10     63218.0
11     55794.0
12     56957.0
13     57081.0
14     61111.0
15     67938.0
16     66029.0
17     83088.0
18     81363.0
19     93940.0
20     91738.0
21     98273.0
22    101302.0
23    113812.0
24    109431.0
25    105582.0
26    116969.0
27    112635.0
28    122391.0
29    121872.0
Name: Salary, dtype: float64

In [11]:
#Linearregression is an ML algo used for linear model which is used to finds weights and relates between independent variables of linear expression and this is imported from sklearn library.
from sklearn.linear_model import LinearRegression 

In [12]:
#It helps to create the empty mind
mind=LinearRegression() 

In [13]:
# Fit function adjusts weights according to data values so that better accuracy can be achieved. After training, the model can be used for predictions
mind.fit(x,y)

LinearRegression()

In [14]:
#It helps to tell the weight of trained model.
mind.coef_

array([9449.96232146])

In [15]:
#It helps to predict the new data with the help of trained model
mind.predict([[2.5]])

array([49417.10600231])

In [16]:
#Joblib can efficiently dump and load numpy arrays but does not require numpy to be installed.
import joblib

In [17]:
#dump the trained model file saved.
joblib.dump(mind,'salary.sk1')

['salary.sk1']

In [18]:
#it helps to tell the weight of the trained model.like m in y=mx+c
mind.coef_

array([9449.96232146])

In [19]:
#It helps to tell the bias of the trained model like constant in y=mx+c
mind.intercept_

25792.20019866871

In [20]:
#Helps to predict the new data.
mind.predict([[2]])

array([44692.12484158])

In [21]:
#Formule accurancy = (predicted value (y)/ actual value (y))*100
43525/44692.12484 * 100


97.3885223757466

In [22]:
# Hence the model is having accuracy of 97.3%

In [23]:
# Hence the model is trained well.